let garantiasRedelec = [
  {
    "codigo": "140076",
    "cliente": "HECTOR ENRIQUE CHARRY AMAYA",
    "clienteId": "7719399",
    "fecha": "2025-06-23",
    "producto": "ICR1924",
    "estado": "PREFINALIZADO",
    "almacen": "METRO-NEIVA",
    "interno": "PHZ547",
    "fechaIngreso": "2025-06-05",
    "productoIngreso": "plancha a vapor one step black decker",
    "lugarDeCompra": "ALMACEN METRO",
    "observaciones": "[domingo, 6 de julio de 2025]DESPACHADO-[domingo, 6 de julio de 2025]reparado"
  },
  {
    "codigo": "140273",
    "cliente": "MARIA FERNANDA PERDOMO",
    "clienteId": "1075224723",
    "fecha": "2025-06-30",
    "producto": "IRBD300",
    "estado": "PREFINALIZADO",
    "almacen": "EXITO NEIVA",
    "interno": "QNL513",
    "fechaIngreso": "2025-06-26",
    "productoIngreso": "plancha black decker",
    "lugarDeCompra": "EXITO",
    "observaciones": ""
  },
  {
    "codigo": "140274",
    "cliente": "YONN ARLEN PEÑA PULIDO",
    "clienteId": "83089242",
    "fecha": "2025-06-30",
    "producto": "IRBD300",
    "estado": "PREFINALIZADO",
    "almacen": "TECNOHOGAR NEIVA",
    "interno": "IWT807",
    "fechaIngreso": "2025-06-19",
    "productoIngreso": "plancha black decker",
    "lugarDeCompra": "TECNOHOGAR",
    "observaciones": ""
  },
  {
    "codigo": "140275",
    "cliente": "LUIS YESID MARTINEZ LAGUNA",
    "clienteId": "12138930",
    "fecha": "2025-06-30",
    "producto": "VCBD603",
    "estado": "AUTORIZADO",
    "almacen": "EXITO NEIVA",
    "interno": "QTG013",
    "fechaIngreso": "2025-06-25",
    "productoIngreso": "aspiradora roja cicleni",
    "lugarDeCompra": "EXITO",
    "observaciones": "[martes, 29 de julio de 2025]le mande la carta a alejandra"
  },
  {
    "codigo": "140909",
    "cliente": "ESPERANZA ROJAS VEGA",
    "clienteId": "36163218",
    "fecha": "2025-07-15",
    "producto": "BL0876-2SDLA",
    "estado": "PREFINALIZADO",
    "almacen": "BRANDLIVE",
    "interno": "VMT605",
    "fechaIngreso": "2025-07-07",
    "productoIngreso": "licuadora blck decker ice crush",
    "lugarDeCompra": "PAGUINA INTERNET",
    "observaciones": ""
  },
  {
    "codigo": "140910",
    "cliente": "DAVID GARCIAS",
    "clienteId": "1075271383",
    "fecha": "2025-07-15",
    "producto": "BLBD210GB",
    "estado": "AUTORIZADO",
    "almacen": "METRO-NEIVA",
    "interno": "GTP146",
    "fechaIngreso": "2025-07-04",
    "productoIngreso": "licuadora black decker",
    "lugarDeCompra": "METRA SANTA LUCIA",
    "observaciones": ""
  },
  {
    "codigo": "140940",
    "cliente": "DIANA MARIA CLAVIJO",
    "clienteId": "55190509",
    "fecha": "2025-07-16",
    "producto": "RC5200M",
    "estado": "PREFINALIZADO",
    "almacen": "TECNOHOGAR NEIVA",
    "interno": "JUZ173",
    "fechaIngreso": "2025-07-12",
    "productoIngreso": "olla arrocera de 2 libras",
    "lugarDeCompra": "TECNOHOGAR",
    "observaciones": ""
  },
  {
    "codigo": "140941",
    "cliente": "MAYERLY VANEGAS CORTES",
    "clienteId": "26433634",
    "fecha": "2025-07-16",
    "producto": "D3035",
    "estado": "AUTORIZADO",
    "almacen": "EXITO SAN PEDRIO NEIVA",
    "interno": "IGH613",
    "fechaIngreso": "2025-07-04",
    "productoIngreso": "plancha black decker suela titanio morada",
    "lugarDeCompra": "EXITO SAN PEDRO",
    "observaciones": ""
  },
  {
    "codigo": "141208",
    "cliente": "NELSON PUENTES VARGAS",
    "clienteId": "83237689",
    "fecha": "2025-07-22",
    "producto": "HF4004B",
    "estado": "TRAMITE",
    "almacen": "MANSION ELECTRODOMESTICOS"
  },
  {
    "codigo": "141386",
    "cliente": "MARIA CAMILA LEON",
    "clienteId": "1075283594",
    "fecha": "2025-07-25",
    "producto": "IR3001",
    "estado": "PENDIENTE AUTORIZACION",
    "almacen": "EXITO NEIVA",
    "interno": "QDH738",
    "fechaIngreso": "2025-07-17",
    "productoIngreso": "plancha black decker impact",
    "lugarDeCompra": "EXITO",
    "observaciones": ""
  }
]