let garantiasRedelec = [
  {
    "codigo": "125861",
    "cliente": "RUBI ESPERANZA TAFURT DIAZ",
    "clienteId": "36183976",
    "fecha": "2024-10-28",
    "producto": "D3035",
    "estado": "PREFINALIZADO",
    "almacen": "K TRONIX SANTA FE",
    "interno": "CJL564",
    "fechaIngreso": "2024-10-22",
    "productoIngreso": "plancha black decker titanio",
    "lugarDeCompra": "KTRONX BOGOTA",
    "observaciones": "[viernes, 24 de enero de 2025]Carta de cambio, no se si entregaron la carta"
  },
  {
    "codigo": "129235",
    "cliente": "SILVIA OVIEDO",
    "clienteId": "29512347",
    "fecha": "2024-12-28",
    "producto": "ICR1924",
    "estado": "PREFINALIZADO",
    "almacen": "TECNOHOGAR",
    "interno": "XKI212",
    "fechaIngreso": "2024-12-12",
    "productoIngreso": "plancha one step azul con blanco",
    "lugarDeCompra": "TECNOHOGAR",
    "observaciones": "[viernes, 24 de enero de 2025]Reparada"
  },
  {
    "codigo": "134378",
    "cliente": "YUDI ALAPE TAPIERO",
    "clienteId": "40079904",
    "fecha": "2025-03-21",
    "producto": "HF4004W",
    "estado": "PREFINALIZADO",
    "almacen": "TECN MAX STORE",
    "interno": "GAS186",
    "fechaIngreso": "2025-03-20",
    "productoIngreso": "freidora black decker",
    "lugarDeCompra": "TECN MAX",
    "observaciones": "[miércoles, 2 de abril de 2025]Despachado-[miércoles, 9 de abril de 2025]Se reemplaza microsuiche"
  },
  {
    "codigo": "136090",
    "cliente": "ISAAC DIAZ",
    "clienteId": "1003829051",
    "fecha": "2025-04-09",
    "producto": "HGS500-LA",
    "estado": "DESPACHADO",
    "almacen": "TECNOGOHAR",
    "interno": "QYS346",
    "fechaIngreso": "2025-04-07",
    "productoIngreso": "plancha titanio",
    "lugarDeCompra": "TECNOGOHAR",
    "observaciones": "[miércoles, 9 de abril de 2025]Pedir automatico y fusible-[miércoles, 23 de abril de 2025]Llega fusible y termostato de moneda-[jueves, 24 de abril de 2025]pedir la  la bomba del agua"
  },
  {
    "codigo": "136153",
    "cliente": "HECTOR JAVIER SALAZAR GARCIA",
    "clienteId": "1081182483",
    "fecha": "2025-04-10",
    "producto": "BLBD210GB",
    "estado": "AUTORIZADO",
    "almacen": "TECNOHOGAR",
    "interno": "PPT718",
    "fechaIngreso": "2025-04-08",
    "productoIngreso": "licuadora black Decker",
    "lugarDeCompra": "ALMACÉN UNIVERSAL",
    "observaciones": ""
  },
  {
    "codigo": "136328",
    "cliente": "KAREN LORENA LEGUIZAMO",
    "clienteId": "1003891363",
    "fecha": "2025-04-11",
    "producto": "CJ4000S",
    "estado": "PREFINALIZADO",
    "almacen": "MISCELANEA JIREH",
    "interno": "MTV073",
    "fechaIngreso": "2025-04-10",
    "productoIngreso": "exprimidor de citricos",
    "lugarDeCompra": "MISCELANEA JIREH",
    "observaciones": ""
  },
  {
    "codigo": "136330",
    "cliente": "YAMILE ROJAS",
    "clienteId": "26575384",
    "fecha": "2025-04-11",
    "producto": "BLBD210GB",
    "estado": "DESPACHADO",
    "almacen": "COMERCIAL BAHIA",
    "interno": "POE904",
    "fechaIngreso": "2025-04-11",
    "productoIngreso": "licuadora black decker",
    "lugarDeCompra": "COMERCIAL BAHIA",
    "observaciones": ""
  },
  {
    "codigo": "137107",
    "cliente": "JHON MARIOA SAENZ",
    "clienteId": "1075799197",
    "fecha": "2025-04-28",
    "producto": "BLBD210GB",
    "estado": "DESPACHADO",
    "almacen": "COMERCIAL BAHIA",
    "interno": "LHJ343",
    "fechaIngreso": "2025-04-16",
    "productoIngreso": "licuadora black Decker",
    "lugarDeCompra": "COMERCIAL HABIA",
    "observaciones": "[lunes, 28 de abril de 2025]motor"
  },
  {
    "codigo": "137108",
    "cliente": "SANTIAGO SAUL GUASCA",
    "clienteId": "1003518600",
    "fecha": "2025-04-28",
    "producto": "HF4004B",
    "estado": "AUTORIZADO",
    "almacen": "TECNOHOGAR neiva",
    "interno": "URV194",
    "fechaIngreso": "2025-04-16",
    "productoIngreso": "freidora black decker",
    "lugarDeCompra": "TECNOHOGAR NEIVA",
    "observaciones": "[lunes, 28 de abril de 2025]tazon"
  },
  {
    "codigo": "137110",
    "cliente": "LAURA CAMILA CALDERON",
    "clienteId": "1007359164",
    "fecha": "2025-04-28",
    "producto": "HF4004B",
    "estado": "DESPACHADO",
    "almacen": "TECNOHOGAR neiva",
    "interno": "EFB491",
    "fechaIngreso": "2025-04-25",
    "productoIngreso": "freidora black decker",
    "lugarDeCompra": "TECNOHOGAR",
    "observaciones": "[lunes, 28 de abril de 2025]MICROSUICHE"
  }
]