let garantiasUniversal = [
  {
    "codigo": "GRT-42301",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1063620018",
    "referencia": "L71300",
    "producto": "VENTILADOR COMPACT FRESH",
    "falla": "Motor Bobinas en corto",
    "s2": "25014305",
    "fecha": "09/09/2025",
    "interno": "PQZ958",
    "fechaIngreso": "2025-09-06",
    "productoIngreso": "ventilador 8\"",
    "lugarDeCompra": "ALMACEN UNIVERSAL",
    "observaciones": ""
  },
  {
    "codigo": "GRT-42295",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1075318169",
    "referencia": "L62090",
    "producto": "LICUADORA ELITE TURBO MAX",
    "falla": "Motor Bobinas en corto,Tarjeta electrónica Sin continuidad",
    "s2": "25014303",
    "fecha": "09/09/2025",
    "interno": "EBV960",
    "fechaIngreso": "2025-09-02",
    "productoIngreso": "licuadora elite turbo max",
    "lugarDeCompra": "CENTRO COMERCIAL UNICO NEIVA",
    "observaciones": ""
  },
  {
    "codigo": "GRT-42294",
    "estado": "Solicitud de validación para cambio de producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1075545222",
    "referencia": "L92801",
    "producto": "BATIDORA EASY MIX",
    "falla": "Batidores No ensambla,Cuerpo Otro",
    "s2": "",
    "fecha": "09/09/2025",
    "interno": "TMM673",
    "fechaIngreso": "2025-09-05",
    "productoIngreso": "batidora manual",
    "lugarDeCompra": "MUEBLES Y ELECTRODOMESTICOS BERNAL",
    "observaciones": ""
  },
  {
    "codigo": "GRT-41746",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "38244421",
    "referencia": "L75545",
    "producto": "VENTILADOR DYNAMIC VENTO",
    "falla": "Motor Motor sin continuidad",
    "s2": "25013886",
    "fecha": "30/08/2025",
    "interno": "OSH326",
    "fechaIngreso": "2025-08-06",
    "productoIngreso": "ventilador universal 3 en 1 dinami",
    "lugarDeCompra": "MAXI MUEBLES",
    "observaciones": "[martes, 2 de septiembre de 2025]esperando repuesto"
  },
  {
    "codigo": "GRT-41745",
    "estado": "Solicitud / producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1109495541",
    "referencia": "L75545",
    "producto": "VENTILADOR DYNAMIC VENTO",
    "falla": "Motor Bobinas en corto,Selector de velocidades Otro",
    "s2": "25014051",
    "fecha": "30/08/2025",
    "interno": "LRO492",
    "fechaIngreso": "2025-08-11",
    "productoIngreso": "ventilador universal dynamic",
    "lugarDeCompra": "UNICO",
    "observaciones": "[lunes, 1 de septiembre de 2025]Validación / Cambio producto"
  },
  {
    "codigo": "GRT-41436",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1006029837",
    "referencia": "L50861",
    "producto": "LICUADORA POTENCY MIX VINO",
    "falla": "Motor Bobinas en corto",
    "s2": "25013655",
    "fecha": "25/08/2025",
    "interno": "VPI954",
    "fechaIngreso": "2025-08-01",
    "productoIngreso": "licuadora universal potency mix roja",
    "lugarDeCompra": "UNICO",
    "observaciones": "[martes, 2 de septiembre de 2025]esperando repuesto"
  },
  {
    "codigo": "GRT-41435",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1003896359",
    "referencia": "L40600",
    "producto": "PLANCHA SECA LA TRADICIONAL",
    "falla": "Térmico Sin continuidad,Termofusible Sin continuidad",
    "s2": "25013654",
    "fecha": "25/08/2025",
    "interno": "ZEU211",
    "fechaIngreso": "2025-08-12",
    "productoIngreso": "plancha universal seca",
    "lugarDeCompra": "TECNOHOGAR",
    "observaciones": "[martes, 2 de septiembre de 2025]esperando repuesto"
  },
  {
    "codigo": "GRT-41434",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "36159791",
    "referencia": "L40600",
    "producto": "PLANCHA SECA LA TRADICIONAL",
    "falla": "Térmico Sin continuidad",
    "s2": "25013653",
    "fecha": "25/08/2025",
    "interno": "FHR239",
    "fechaIngreso": "2025-08-13",
    "productoIngreso": "plancha universal seca",
    "lugarDeCompra": "COMERCIALIZADORA SANDRA DIAZ TOVAR",
    "observaciones": "[martes, 2 de septiembre de 2025]esperando repuesto"
  },
  {
    "codigo": "GRT-40339",
    "estado": "Por entregar",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "36155687",
    "referencia": "L40600",
    "producto": "PLANCHA SECA LA TRADICIONAL",
    "falla": "Térmico Sin continuidad,Termostato Otro",
    "s2": "25012654",
    "fecha": "06/08/2025",
    "interno": "AVW582",
    "fechaIngreso": "2025-07-26",
    "productoIngreso": "plancha universal seca",
    "lugarDeCompra": "COMERCIAL BAHIA",
    "observaciones": "[viernes, 15 de agosto de 2025]falta reparar-[sábado, 30 de agosto de 2025]REPARADA"
  },
  {
    "codigo": "GRT-40338",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1075237206",
    "referencia": "L83696",
    "producto": "EXPRIMIDOR CITRUS MAX",
    "falla": "Motor Colector en corto",
    "s2": "25012653",
    "fecha": "06/08/2025",
    "interno": "YBY954",
    "fechaIngreso": "2025-07-29",
    "productoIngreso": "exprimidor de citricos",
    "lugarDeCompra": "CACHARRERIA EL REY DE LOS PRECIOS BAJOS",
    "observaciones": "[viernes, 15 de agosto de 2025]MOTOR CON PIÑON martes 5 de agosto-[sábado, 30 de agosto de 2025]MOTOR QUE LLEGÓ... LLEGÓ SIN PIÑONES... ADEMAS NO FUNCIONA"
  },
  {
    "codigo": "GRT-39110",
    "estado": "Por entregar",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "40620745",
    "referencia": "L85320",
    "producto": "OLLA ARROCERA LA TRADICIONAL10",
    "falla": "Cuerpo Otro",
    "s2": "25011545",
    "fecha": "15/07/2025",
    "interno": "LKB004",
    "fechaIngreso": "2025-07-14",
    "productoIngreso": "olla arrocera negra de 2 libras",
    "lugarDeCompra": "ALAMCENES UNIVERSAL",
    "observaciones": "[miércoles, 6 de agosto de 2025]Arrocera nueva"
  }
]