let garantiasUniversal = [
  {
    "codigo": "GRT-68822",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "12134173",
    "referencia": "L85363",
    "producto": "OLLA ARROCERA RUSTIK BLACK",
    "falla": "Termofusible Sin continuidad",
    "s2": "NO APLICA S2!",
    "fecha": "21/02/2026",
    "interno": "GNC575",
    "fechaIngreso": "2026-02-09",
    "productoIngreso": "arrocera rustik black",
    "lugarDeCompra": "UNICO",
    "observaciones": "[sábado, 21 de febrero de 2026]reparada con fusible prestado"
  },
  {
    "codigo": "GRT-68817",
    "estado": "Solicitud de validación para cambio de producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "83169499",
    "referencia": "L75545",
    "producto": "VENTILADOR DYNAMIC VENTO",
    "falla": "Cuerpo Otro,Motor Colector en corto",
    "s2": "",
    "fecha": "21/02/2026",
    "interno": "ZGZ746",
    "fechaIngreso": "2026-02-16",
    "productoIngreso": "universal dynamic negro",
    "lugarDeCompra": "UNICO",
    "observaciones": "[sábado, 21 de febrero de 2026]se pide cambio"
  },
  {
    "codigo": "GRT-68279",
    "estado": "Solicitud / producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1075289460",
    "referencia": "L37706",
    "producto": "OLLA A PRESIÓN TRIEXPRESS 5.6L",
    "falla": "Cuerpo Quebrado",
    "s2": "26002648",
    "fecha": "12/02/2026",
    "interno": "USI926",
    "fechaIngreso": "2026-02-10",
    "productoIngreso": "olla a presion de 5.6 litros cierre externo",
    "lugarDeCompra": "ALMACENES UNIVERSAL",
    "observaciones": "[jueves, 12 de febrero de 2026]asas o cambio"
  },
  {
    "codigo": "GRT-67792",
    "estado": "Por entregar",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "36067856",
    "referencia": "L27630",
    "producto": "OLLA PRESION LPC CI 6L V2",
    "falla": "Cuerpo Deformado",
    "s2": "26002014",
    "fecha": "04/02/2026",
    "interno": "WSC977",
    "fechaIngreso": "2026-02-02",
    "productoIngreso": "olla pitadora tradicional",
    "lugarDeCompra": "EXITO",
    "observaciones": "[miércoles, 4 de febrero de 2026]se pidio cambio-[jueves, 12 de febrero de 2026]Llega olla a presion"
  },
  {
    "codigo": "GRT-67783",
    "estado": "Solicitud / producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "12202172",
    "referencia": "L50850",
    "producto": "LICUADORA MASS VITAL",
    "falla": "Selector de velocidades En corto",
    "s2": "26002011",
    "fecha": "04/02/2026",
    "interno": "FBP757",
    "fechaIngreso": "2026-01-28",
    "productoIngreso": "lucuadora mass vital",
    "lugarDeCompra": "CRISTIAN COMUNICACIONES",
    "observaciones": "[miércoles, 4 de febrero de 2026]suiche  o cambio"
  },
  {
    "codigo": "GRT-67528",
    "estado": "Por entregar",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1075260603",
    "referencia": "L50803",
    "producto": "LICUADORA LA TRADICIONAL",
    "falla": "Motor Bobinas en corto",
    "s2": "26001734",
    "fecha": "31/01/2026",
    "interno": "ZWV504",
    "fechaIngreso": "2025-12-27",
    "productoIngreso": "motor licuadora universal",
    "lugarDeCompra": "ELECTRODOMESTICOS MANA",
    "observaciones": "[sábado, 31 de enero de 2026]se pide motor-[jueves, 12 de febrero de 2026]Llega licuadora"
  },
  {
    "codigo": "GRT-67333",
    "estado": "Por entregar",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "55165679",
    "referencia": "L71150",
    "producto": "VENTILADOR DE TORRE",
    "falla": "Motor Bobinas en corto,Tarjeta electrónica En corto",
    "s2": "26001180",
    "fecha": "27/01/2026",
    "interno": "FUD733",
    "fechaIngreso": "2026-01-20",
    "productoIngreso": "ventilador de torre",
    "lugarDeCompra": "ALMACENES UNIVERSAL",
    "observaciones": "[martes, 27 de enero de 2026]se pide motores y tarjeta-[miércoles, 4 de febrero de 2026]llega motor, motor, tarjeta-[jueves, 12 de febrero de 2026]reparado"
  },
  {
    "codigo": "GRT-67199",
    "estado": "Por entregar",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1075243622",
    "referencia": "L62070",
    "producto": "LICUADORA ULTRA+VASO PICATODO",
    "falla": "Motor Bobinas en corto",
    "s2": "26001657",
    "fecha": "26/01/2026",
    "interno": "GSR788",
    "fechaIngreso": "2026-01-26",
    "productoIngreso": "licuadora  universal  ultra",
    "lugarDeCompra": "ALAMCENES UNIVERSAL",
    "observaciones": "[miércoles, 4 de febrero de 2026]se pidio motor o cambio-[jueves, 12 de febrero de 2026]Llega licuadora"
  },
  {
    "codigo": "GRT-66389",
    "estado": "Por entregar",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1117526434",
    "referencia": "L75680",
    "producto": "VENTILADOR FRESH ULT  C REMOTO",
    "falla": "Motor Bobinas en corto",
    "s2": "26000328",
    "fecha": "10/01/2026",
    "interno": "CUA250",
    "fechaIngreso": "2026-01-08",
    "productoIngreso": "ventilador universal",
    "lugarDeCompra": "ALMACEN UNIVERSAL",
    "observaciones": "[sábado, 10 de enero de 2026]pedir motor-[lunes, 19 de enero de 2026]llega motor-[miércoles, 18 de febrero de 2026]reparado"
  },
  {
    "codigo": "GRT-65799",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "37684907",
    "referencia": "L40600",
    "producto": "PLANCHA SECA LA TRADICIONAL",
    "falla": "Termostato Sin continuidad ",
    "s2": "25019961",
    "fecha": "24/12/2025",
    "interno": "NWT535",
    "fechaIngreso": "2025-12-22",
    "productoIngreso": "plancha seca universal",
    "lugarDeCompra": "ALMACEN UNIVERSAL",
    "observaciones": "[lunes, 5 de enero de 2026]llega termostato"
  },
  {
    "codigo": "GRT-65615",
    "estado": "Solicitud de validación para cambio de producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "36452836",
    "referencia": "L40840",
    "producto": "PLANCHA A VAPOR CERAMIC HOME",
    "falla": "Resistencia Sin continuidad,Termofusible Sin continuidad,Termostato Sin continuidad ",
    "s2": "",
    "fecha": "18/12/2025",
    "interno": "LDH008",
    "fechaIngreso": "2025-12-15",
    "productoIngreso": "plancha univesal",
    "lugarDeCompra": "SAN ANDRESITO",
    "observaciones": "[jueves, 18 de diciembre de 2025]se pidió cambio-[miércoles, 14 de enero de 2026]LANDER: está en gestión de producto sustituto. Ya le voy a informar a la compañera del BPO para que, por favor, nos ayude con la gestión lo más pronto posible."
  },
  {
    "codigo": "GRT-64939",
    "estado": "Solicitud de validación para cambio de producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1010138508",
    "referencia": "L85643",
    "producto": "OLLA PRESION ELECTRICA 3L",
    "falla": "Resistencia Sin continuidad",
    "s2": "",
    "fecha": "05/12/2025",
    "interno": "DFS073",
    "fechaIngreso": "2025-12-01",
    "productoIngreso": "olla presión electrica",
    "lugarDeCompra": "UNICO NEIVA",
    "observaciones": "[jueves, 4 de diciembre de 2025]dice que la repararon, pero tambien se pidió cambio-[miércoles, 14 de enero de 2026]LANDER: Este caso se está tramitando con la consumidora para el producto sustituto. Estamos a la espera de que ella elija el producto y nos brinde la información necesaria para proceder con el pedido."
  }
]