let garantiasUniversal = [
  {
    "codigo": "GRT-42630",
    "estado": "Por entregar",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "7722981",
    "referencia": "L50803",
    "producto": "LICUADORA LA TRADICIONAL",
    "falla": "Motor Bobinas en corto,Selector de velocidades En corto",
    "s2": "25015403",
    "fecha": "15/09/2025",
    "interno": "THI911",
    "fechaIngreso": "2025-08-30",
    "productoIngreso": "licuadora",
    "lugarDeCompra": "EXITO",
    "observaciones": "[domingo, 14 de septiembre de 2025]pedir motor y teclado-[domingo, 14 de septiembre de 2025]se pidio producto-[miércoles, 1 de octubre de 2025]llega licuadora nueva"
  },
  {
    "codigo": "GRT-42301",
    "estado": "Por entregar",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1063620018",
    "referencia": "L71300",
    "producto": "VENTILADOR COMPACT FRESH",
    "falla": "Motor Bobinas en corto",
    "s2": "25014305",
    "fecha": "09/09/2025",
    "interno": "PQZ958",
    "fechaIngreso": "2025-09-06",
    "productoIngreso": "ventilador 8\"",
    "lugarDeCompra": "ALMACEN UNIVERSAL",
    "observaciones": "[domingo, 14 de septiembre de 2025]llegó motor para cambiar-[domingo, 28 de septiembre de 2025]reparado"
  },
  {
    "codigo": "GRT-42295",
    "estado": "En reparación",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1075318169",
    "referencia": "L62090",
    "producto": "LICUADORA ELITE TURBO MAX",
    "falla": "Motor Bobinas en corto,Tarjeta electrónica Sin continuidad",
    "s2": "25014303",
    "fecha": "09/09/2025",
    "interno": "EBV960",
    "fechaIngreso": "2025-09-02",
    "productoIngreso": "licuadora elite turbo max",
    "lugarDeCompra": "CENTRO COMERCIAL UNICO NEIVA",
    "observaciones": "[domingo, 14 de septiembre de 2025]se pidio motor y tarjeta"
  },
  {
    "codigo": "GRT-42294",
    "estado": "Solicitud / producto",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "1075545222",
    "referencia": "L92801",
    "producto": "BATIDORA EASY MIX",
    "falla": "Batidores No ensambla,Cuerpo Otro",
    "s2": "25014810",
    "fecha": "09/09/2025",
    "interno": "TMM673",
    "fechaIngreso": "2025-09-05",
    "productoIngreso": "batidora manual",
    "lugarDeCompra": "MUEBLES Y ELECTRODOMESTICOS BERNAL",
    "observaciones": "[domingo, 14 de septiembre de 2025]se pidio piñones-[domingo, 14 de septiembre de 2025]se pidio producto"
  },
  {
    "codigo": "GRT-41746",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "38244421",
    "referencia": "L75545",
    "producto": "VENTILADOR DYNAMIC VENTO",
    "falla": "Motor Motor sin continuidad",
    "s2": "25013886",
    "fecha": "30/08/2025",
    "interno": "OSH326",
    "fechaIngreso": "2025-08-06",
    "productoIngreso": "ventilador universal 3 en 1 dinami",
    "lugarDeCompra": "MAXI MUEBLES",
    "observaciones": "[martes, 2 de septiembre de 2025]esperando repuesto"
  },
  {
    "codigo": "GRT-41436",
    "estado": "Solicitud / repuesto",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1006029837",
    "referencia": "L50861",
    "producto": "LICUADORA POTENCY MIX VINO",
    "falla": "Motor Bobinas en corto",
    "s2": "25013655",
    "fecha": "25/08/2025",
    "interno": "VPI954",
    "fechaIngreso": "2025-08-01",
    "productoIngreso": "licuadora universal potency mix roja",
    "lugarDeCompra": "UNICO",
    "observaciones": "[martes, 2 de septiembre de 2025]esperando repuesto"
  },
  {
    "codigo": "GRT-40338",
    "estado": "En reparación",
    "tipo": "REPARACIONES (GARANTIAS)",
    "clienteId": "1075237206",
    "referencia": "L83696",
    "producto": "EXPRIMIDOR CITRUS MAX",
    "falla": "Motor Colector en corto",
    "s2": "25012653",
    "fecha": "06/08/2025",
    "interno": "YBY954",
    "fechaIngreso": "2025-07-29",
    "productoIngreso": "exprimidor de citricos",
    "lugarDeCompra": "CACHARRERIA EL REY DE LOS PRECIOS BAJOS",
    "observaciones": "[viernes, 15 de agosto de 2025]MOTOR CON PIÑON martes 5 de agosto-[sábado, 30 de agosto de 2025]MOTOR QUE LLEGÓ... LLEGÓ SIN PIÑONES... ADEMAS NO FUNCIONA"
  },
  {
    "codigo": "GRT-39110",
    "estado": "Por entregar",
    "tipo": "CAMBIO PRODUCTO",
    "clienteId": "40620745",
    "referencia": "L85320",
    "producto": "OLLA ARROCERA LA TRADICIONAL10",
    "falla": "Cuerpo Otro",
    "s2": "25011545",
    "fecha": "15/07/2025",
    "interno": "LKB004",
    "fechaIngreso": "2025-07-14",
    "productoIngreso": "olla arrocera negra de 2 libras",
    "lugarDeCompra": "ALAMCENES UNIVERSAL",
    "observaciones": "[miércoles, 6 de agosto de 2025]Arrocera nueva"
  }
]